### ISSUE TITLE
rooms empty

### ISSUE THREAD

**Issue by baddot** [imlinus/Sexy-Ionic-Firebase-IOS-Android-Auth-Chat-with-Rooms#1]
how do you fix your rooms ?

**Comment by imlinus** [comment]
Hi mate!

Im building it so that you will add a room when you sign up on the web-app, but if you need a quick way to add rooms, I'd just paste this in to the code:

Services.js line 119 - 140
`
.factory('Rooms', function($rootScope) {
    //Created data Rooms
    var dataRooms = [{
        id: 1,
        icon: 'ion-university',
        name: 'Academics'
    },{
        id: 2,
        icon: 'ion-camera',
        name: 'Photography'
    },{
        id: 3,
        icon: 'ion-music-note',
        name: 'Music'
    },{
        id: 4,
        icon: 'ion-woman',
        name: 'Fashion'
    },{
        id: 5,
        icon: 'ion-plane',
        name: 'Travel'
    }];
    for (var i = 0; i < dataRooms.length; i++) {
        var newPostKey = rootRef.child('rooms').push().key;
        rootRef.child('rooms/' + dataRooms[i].id).set({
            id: dataRooms[i].id,
            codeId: newPostKey,
            icon: dataRooms[i].icon,
            name: dataRooms[i].name
        }).then(function(data){
            //console.log(data);
        },function(err){
            //console.log(err);
        });
    }
    //End Created Data rooms

    var allRoom = rootRef.child("rooms").once('value');

    return {
        all: function() {
            // get all room
            return allRoom;
        },
        get: function(roomId) {
            // Simple index lookup
            return rootRef.child("rooms/" + roomId).once('value');
        }
    }
});
`

Cheers!

**Comment by imlinus** [comment]
So basically what I want to to is use the same FireBase for this one: https://github.com/imlinus/Sexy-AngularFire-Auth-Chat-with-Rooms

So when you sign up there, on the web. you create a room, which you can share with your friends (who will use their phones)

I hope you understand my thinking a bit better now. If you need anything else, just let me know!

Cheers

**Comment by baddot** [comment]
yes i understood totally

how do you make pirvate msg ?

**Comment by imlinus** [comment]
Hey,

Sorry, but it's not possible yet at the time. however I can recommend you to follow this tutorial made by google, I'm sure you'll be able to implement it in a few lines of code :)

https://codelabs.developers.google.com/codelabs/cloud-firebase-chat/#0

Cheers

**Comment by baddot** [comment]
hi sure thanks! ill take alook at there
